### ISSUE TITLE
建议增加example

### ISSUE THREAD

**Issue by rivers-fighting** [esastack/esa-httpserver#17]
用test目录下的代码尝试启动服务，但是服务启动几秒钟后，进程就终止了，不知道用法哪里不对。能不能把esa和netty做性能测试的源码和相关参数配置也提交上来，谢谢 ：）

**Comment by rivers-fighting** [comment]
![image](https://user-images.githubusercontent.com/85326030/128308022-7e02dd7c-a0ce-4eb6-bfc8-320364854fc4.png)

**Comment by alalag1** [comment]
@rivers-fighting  进程终止的原因是HttpServer所使用的线程都是daemon线程，因此当main线程退出后程序就自动退出了
两种方案
1. 使用`HttpServer#await()` 或 `HttpServer#awaitUninterruptibly()`方法，阻塞等待server退出

```java
HttpServer.create(ServerOptionsConfigure.newOpts()
        .daemon(false)
        .configured())
        .handle(r -> {
            // ...
        })
        .listen(8080);
```

2. 启动HttpServer时传入配置，并且将`ServerOptions#daemon`属性设置为`false`

```java
HttpServer.create()
        .handle(r -> {
            // ...
        })
        .listen(8080)
        .awaitUninterruptibly();
```

> 现在文档相对比较匮乏， 后续优化相关文档
